version: 0.2

env:
  variables:
    POST_CHECKS: "Temp_Danny_TestBuild"
    TEST_COMMIT: '/CodeBuild/GitCommit/Input'    

phases:
  build:
    commands:
      - mvn package
      - chmod a+x src/Buildscripts/trigger_codebuild.sh
      - src/Buildscripts/trigger_codebuild.sh
artifacts:
  files:
    - '**/*'