version: 0.2
phases:
  build:
    commands:
      - mvn package
      - sleep 10
      - chmod a+x src/Buildscripts/trigger_codebuild.sh
      - src/Buildscripts/trigger_codebuild.sh
artifacts:
  files:
    - '**/*'