version: 0.2

env:
  variables:
    POST_CHECKS: "Temp_WebTestsPipeline"
    TEST_COMMIT: '/CodeBuild/GitCommit/Input'    

phases:
  build:
    commands:
      - chmod a+x src/Buildscripts/trigger_pipeline.sh
      - chmod a+x src/Buildscripts/generate_commit.sh
      - src/Buildscripts/generate_commit.sh
      - src/Buildscripts/trigger_pipeline.sh
artifacts:
  files:
    - '**/*'